# Generated by Django 4.2.1 on 2023-05-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_format_img', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesformat',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
