# Generated by Django 4.2.1 on 2023-05-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_format_img', '0002_imagesformat_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesformat',
            name='img',
            field=models.ImageField(null=True, upload_to='./public/img/'),
        ),
    ]
